---
- hosts: test_240
  remote_user: sysadmin
  gather_facts: No
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: copy filebeat.7.7.rpm to destnestion host
    copy: src=/software/filebeat-7.7.0-x86_64.rpm dest=/software/ mode=0755
  - name: install filebeat by rpm
    shell: yum -y install /software/filebeat-7.7.0-x86_64.rpm
  - name: starting the serive
    service: name=filebeat state=started enabled=yes
